# ========================
# Clash-ALL ä¼˜åŒ–é…ç½®
# ========================

# æœºåœºèŠ‚ç‚¹è®¢é˜…

proxy-providers:

  ä¼˜é€Ÿé€š:
    url: "https://23.158.136.185/api/v1/client/subscribe?token=99c17bd4414cff5b1fa4f7b75cf38651"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

  ç‰›é€¼:
    url: "https://zhuzhuzhu.whtjdasha.com/api/v1/client/subscribe?token=3e0a55abc8e638572b4ccaec2de310dd"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

  å…‰é€Ÿ:
    url: "https://rssgs.ei38d3if3.xyz/index/21790e59c41de081ac77e82b31508fa2"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}

# ========================
# ä¸»è¦ç«¯å£è®¾ç½®
# ========================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895

allow-lan: true
mode: rule
log-level: info

external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-name: zashboard
external-ui-url: https://gh-proxy.com/github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip
secret: "miss7042"

# ========================
# DNS è®¾ç½®
# ========================
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.20.0.1/16
  nameserver:
    - 223.5.5.5
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - +.lan
    - +.local
    - geosite:cn
# ç‰›é€¼   
    - +.idsduf.com  
    - +.66jc.top
# æé€Ÿé€š        
    - +.gfw.gg

ipv6: true

# ========================
# TUN æ¨¡å—
# ========================
tun:
  enable: true
  stack: gvisor
  device: utun
  endpoint-independent-nat: true
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false

profile:
  store-selected: true
  store-fake-ip: true

# ========================
# ç­–ç•¥ç»„å®šä¹‰
# ========================
default: &default
  type: select
  proxies: [ç›´è¿,æ‰€æœ‰-æ‰‹åŠ¨,æ‰€æœ‰-è‡ªåŠ¨,é¦™æ¸¯-è‡ªåŠ¨,å°æ¹¾-è‡ªåŠ¨,æ—¥æœ¬-è‡ªåŠ¨,æ–°åŠ å¡-è‡ªåŠ¨,éŸ©å›½-è‡ªåŠ¨,ç¾å›½-è‡ªåŠ¨,å…¶ä»–-è‡ªåŠ¨,æ‹’ç»]
proxy-groups:
  - {name: æ‰€æœ‰-æ‰‹åŠ¨, type: select, include-all: true, filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"}
  - {name: æ‰€æœ‰-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"}
  - {name: ChatGPT, type: select, proxies: [ç¾å›½-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: Meta AI, type: select, proxies: [ç¾å›½-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: GitHub, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: Telegram, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: Twitter(X), type: select, proxies: [ç¾å›½-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: WhatsApp, type: select, proxies: [ç¾å›½-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: Facebook, type: select, proxies: [ç¾å›½-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: YouTube, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: TikTok, type: select, proxies: [ç¾å›½-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: Microsoft, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: Google, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: å›½å¤–, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: å›½å†…, <<: *default}
  - {name: å…¶ä»–, type: select, proxies: [æ‰€æœ‰-è‡ªåŠ¨, æ‰€æœ‰-æ‰‹åŠ¨, ç¾å›½-è‡ªåŠ¨, ç›´è¿, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-è‡ªåŠ¨, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-è‡ªåŠ¨, å…¶ä»–-è‡ªåŠ¨, æ‹’ç»]}
  - {name: é¦™æ¸¯-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"}
  - {name: å°æ¹¾-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"}
  - {name: æ—¥æœ¬-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"}
  - {name: æ–°åŠ å¡-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"}
  - {name: éŸ©å›½-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"}
  - {name: ç¾å›½-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"}
  - {name: å…¶ä»–-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK)).)*$"}

# ========================
# è§„åˆ™å¼•æ“ï¼ˆrulesï¼‰
# ========================
rules:
  - RULE-SET,ChatGPT / Domain,ChatGPT
  - RULE-SET,Meta AI / Domain,Meta AI
  - RULE-SET,GitHub / Domain,GitHub
  - RULE-SET,Telegram / Domain,Telegram
  - RULE-SET,Telegram / IP,Telegram,no-resolve
  - RULE-SET,Twitter / Domain,Twitter(X)
  - RULE-SET,WhatsApp / Domain,WhatsApp
  - RULE-SET,Facebook / Domain,Facebook  
  - RULE-SET,Microsoft / Domain,Microsoft
  - RULE-SET,Youtube / Domain,YouTube
  - RULE-SET,TikTok / Domain,TikTok
  - RULE-SET,Google / Domain,Google
  - RULE-SET,Google / IP,Google,no-resolve
  - RULE-SET,Proxy / Domain,å›½å¤–
  - RULE-SET,Globe / Domain,å›½å¤–  
  - RULE-SET,Direct / Domain,å›½å†…
  - RULE-SET,China / Domain,å›½å†…
  - RULE-SET,China / IP,å›½å†…,no-resolve
  - RULE-SET,Private / Domain,å›½å†…
  - MATCH,å…¶ä»–

# ========================
# è§„åˆ™é›†æä¾›è€…
# ========================
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  ChatGPT / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"}
  Meta AI / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/MetaAi.list"}
  Copilot / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Copilot.list"}
  Gemini / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Gemini.list"}
  GitHub / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"}
  Telegram / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs"}  
  Telegram / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"}
  Twitter / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.mrs"}
  WhatsApp / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list"}
  Facebook / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/facebook.mrs"}
  Microsoft / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"}
  TikTok / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"}
  Proxy / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list"}
  Globe / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"} 
  Direct / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list"}
  China / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"}
  China / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"}
  Private / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"}
  Block / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Block.list"}
  Nvidia / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nvidia/Nvidia.list"}
  Crunchyroll / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Crunchyroll.list"}
  Reddit / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/reddit.mrs"}

  Youtube / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"}  
  Google / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"}  
  Google / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"}